### ISSUE TITLE
Reports with Sub-Reports are not being generated

### ISSUE THREAD

**Issue by chrisrochc** [okohll/RunJasperReports#1]
I have been able to successfully use RunJasperReports v1.1.3.1 on single reports, but have encountered an issue where a report with a sub-report generates an excecption. I am able to view the report properly in iReport, but it fails when i try to run it from the command line. Can RunjasperReports currently support sub-reports and if not will there be any chance that feature will be implemented in the near future?

Environment:
Windows XP
Java 6

Command being run:

C:\Documents and Settings\Administrator>java -jar "C:\Software\Jasper\jasper-cli\RunJasperReports.jar" -dbname "database" -dbhost "localhost" -dbuser "dbuser" -dbpass "password" -dbtype mysql -output pdf -folder "C:\Program Files\Zend\Apache2\
htdocs\vmbase\core\private\data\temp" -filename "8285C39AF0FD532B348A142C9ADEC7625D3C1162" -reports "C:\Program Files\Ze
nd\Apache2\htdocs\vmbase\core\private\data\reports\queue_process_tran_process.jrxml" -params "start_date=string:1900-01-01 00:00:00,end_date=string:3000-01-01 23:59:59,SUBREPORT_DIR=string:C:\Program Files\Zend\Apache2\htdocs\vmbase\core\pr
ivate\data\reports,current_user=string:webuser06"

Output generated:

Report parameters are: {SUBREPORT_DIR=C:\Program Files\Zend\Apache2\htdocs\vmbase\core\private\data\reports, end_date=30
00-01-01 23:59:59, current_user=webuser06, start_date=1900-01-01 00:00:00}
Going to generate report C:\Program Files\Zend\Apache2\htdocs\vmbase\core\private\data\temp\8285c39af0fd532b348a142c9ade
c7625d3c1162.pdf
Read input file C:\Program Files\Zend\Apache2\htdocs\vmbase\core\private\data\reports\queue_process_tran_process.jrxml
Compiled report from file C:\Program Files\Zend\Apache2\htdocs\vmbase\core\private\data\reports\queue_process_tran_proce
ss.jrxml
About to connect to database using connection string jdbc:mysql://localhost/database
Connected to database database
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/callsite/CallSiteArray
        at queue_process_tran_process_1297462616401_251418.$createCallSiteArray(calculator_queue_process_tran_process_12
97462616401_251418)
        at queue_process_tran_process_1297462616401_251418.$getCallSiteArray(calculator_queue_process_tran_process_12974
62616401_251418)
        at queue_process_tran_process_1297462616401_251418.<init>(calculator_queue_process_tran_process_1297462616401_25
1418)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at net.sf.jasperreports.engine.design.JRAbstractJavaCompiler.loadEvaluator(JRAbstractJavaCompiler.java:98)
        at net.sf.jasperreports.engine.design.JRAbstractCompiler.loadEvaluator(JRAbstractCompiler.java:320)
        at net.sf.jasperreports.engine.JasperCompileManager.loadEvaluator(JasperCompileManager.java:240)
        at net.sf.jasperreports.engine.JasperCompileManager.loadEvaluator(JasperCompileManager.java:260)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.createEvaluator(JRFillSubreport.java:391)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.loadReportEvaluator(JRFillSubreport.java:379)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.evaluateSubreport(JRFillSubreport.java:348)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.evaluate(JRFillSubreport.java:263)
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:258)
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:499)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummaryNoLastFooterNewPage(JRVerticalFiller.java:1169)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummary(JRVerticalFiller.java:1034)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportEnd(JRVerticalFiller.java:300)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:134)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:942)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:841)
        at net.sf.jasperreports.engine.fill.JRFiller.fillReport(JRFiller.java:58)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:417)
        at com.gtwm.jasperexecute.RunJasperReports.generateReport(RunJasperReports.java:292)
        at com.gtwm.jasperexecute.RunJasperReports.generatePdfReport(RunJasperReports.java:108)
        at com.gtwm.jasperexecute.RunJasperReports.main(RunJasperReports.java:466)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.callsite.CallSiteArray
        at java.lang.ClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
        ... 30 more

**Comment by okohll** [comment]
Hello,

There is an issue with subreports I've yet to write up in the FAQ at www.agilebase.co.uk/opensource. Basically, I found you have to precompile  
them e.g. using ireport and reference the compiled .class version from  
the main report XML file. I can't remember the exact procedure but let  
me know if that helps. I also had this email from a user a few weeks ago which could be relevant if you're using Groovy:

Oliver,
Thanks for getting back to me, it was very helpful. I managed to get it
working in the end by converting the subreports to compile with java instead
of groovy. The main report was still being compiled with groovy but it was
the subreports that were causing an issue. 

---

By the way, would you like to be added to the RJR announcements list? Please send an email to oliver at agilebase.co.uk if so.

Regards
Oliver Kohll

**Comment by chrisrochc** [comment]
Thanks for the response, I will check out that option right away.
