### ISSUE TITLE
Unable to work with local language like Hindi,kannada etc, I am Using Akshar Unicode

### ISSUE THREAD

**Issue by sachinmanjule** [okohll/RunJasperReports#4]
Exception in thread "main" net.sf.jasperreports.engine.JRRuntimeException: com.lowagie.text.DocumentException: Font '' with 'Identity-H' is not recognized.
    at net.sf.jasperreports.engine.export.JRPdfExporter.getFont(JRPdfExporter.java:2080)
    at net.sf.jasperreports.engine.export.JRPdfExporter.getChunk(JRPdfExporter.java:1817)
    at net.sf.jasperreports.engine.export.JRPdfExporter.getPhrase(JRPdfExporter.java:1786)
    at net.sf.jasperreports.engine.export.SimplePdfTextRenderer.getPhrase(SimplePdfTextRenderer.java:89)
    at net.sf.jasperreports.engine.export.SimplePdfTextRenderer.render(SimplePdfTextRenderer.java:99)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportText(JRPdfExporter.java:2176)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:860)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportPage(JRPdfExporter.java:820)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:697)
    at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:398)
    at net.sf.jasperreports.engine.JasperExportManager.exportToPdfStream(JasperExportManager.java:191)
    at net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfStream(JasperExportManager.java:527)
    at com.gtwm.jasperexecute.RunJasperReports.generatePdfReport(RunJasperReports.java:113)
    at com.gtwm.jasperexecute.RunJasperReports.main(RunJasperReports.java:466)
Caused by: com.lowagie.text.DocumentException: Font '' with 'Identity-H' is not recognized.
    at com.lowagie.text.pdf.BaseFont.createFont(Unknown Source)
    at com.lowagie.text.pdf.BaseFont.createFont(Unknown Source)
    at com.lowagie.text.pdf.BaseFont.createFont(Unknown Source)
    at net.sf.jasperreports.engine.export.JRPdfExporter.getFont(JRPdfExporter.java:2068)

**Comment by sachinmanjule** [comment]
I done
